language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

sudo: false

cache:
  directories:
    - $HOME/wheelhouse

install:
  - pip wheel --find-links=$HOME/wheelhouse -r requirements.txt --wheel-dir=$HOME/wheelhouse
  - pip install --no-index --find-links=$HOME/wheelhouse -r requirements.txt

script:
  - coverage run $(which py.test) libcloudcore
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then flake8 libcloudcore; fi

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
